- name: create group
  group:
    name: "{{ minio_group }}"
    state: present

- name: create user
  user:
    name: "{{ minio_user }}"
    state: present
    shell: /bin/bash
    groups: "{{ minio_group }}"


